# producer configuration file h1
---
  filePath: use-cases/app-testing/word-count/inputTopic1/
  topicName: Greetings
  totalMessages: 1
  producerInstances: 1
  # messageRate: 1.0
  # acks: 1
  # compression: None
  # batchSize: 16384
  # linger: 0
  # requestTimeout: 30000
...