# topic configuration file
---
  topicName: topic-0
  topicBroker: 1
  topicPartition: 1
  topicReplica: 1
  brokerId: h2
...
# ---
#   topicName: topic-1
#   topicBroker: 1
#   topicPartition: 1
#   topicReplica: 1
# ...
