# topic configuration file
---
  topicName: Greetings
  topicBroker: 2
  topicPartition: 1
  topicReplica: 1
...
---
  topicName: Soccer
  topicBroker: 2
  topicPartition: 1
  topicReplica: 1
...
---
  topicName: outputTopic
  topicBroker: 2
  topicPartition: 1
  topicReplica: 1
...